# Example configuration for interactive planning mode
# Copy to .cr.yaml or ~/.config/cr/cr.yaml and customize

providers:
  openai:
    enabled: true
    model: gpt-4o-mini
    apiKey: ${OPENAI_API_KEY}

  anthropic:
    enabled: true
    model: claude-3-5-sonnet-20241022
    apiKey: ${ANTHROPIC_API_KEY}

# Planning configuration
planning:
  enabled: true
  provider: openai  # Can be: openai, anthropic, gemini, ollama
  model: gpt-4o-mini  # Optional: override provider's default model
  maxQuestions: 5  # Maximum number of questions to ask (default: 5)
  timeout: 30s  # Timeout for planning phase (default: 30s)

# Store configuration (recommended for cost tracking)
store:
  enabled: true
  path: ~/.local/share/cr/reviews.db

# Observability (recommended for debugging)
observability:
  logging:
    enabled: true
    level: info  # debug, info, error
    format: human  # json, human
    redactAPIKeys: true

# Output configuration
output:
  directory: reviews

# Git configuration
git:
  repositoryDir: .
