version: 2

project_name: code-reviewer

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cr
    main: ./cmd/cr
    binary: cr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/bkyoung/code-reviewer/internal/version.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*
      - docs/GITHUB_ACTION_SETUP.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bkyoung
    name: code-reviewer
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
