name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod download
      - name: Format
        run: |
          fmt_output=$(gofmt -l .)
          if [ -n "$fmt_output" ]; then
            echo "Please run gofmt on the following files:"
            echo "$fmt_output"
            exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
